(function () {
  "use strict";

  window.GENESIS_TEAM = [
    { slug: "sahil-khanna", name: "Mr Sahil Khanna", role: "Founder · Mentor · Educator · Physics", title: "Still a Teacher.", image: "assets/Sahil Khanna.jpeg", intro: "Genesis has grown, but the classroom remains at the centre of Sahil's work.", bio: "After 16+ years in education and mentoring 15,000+ students and parents, Sahil continues to teach Physics, mentor students, conduct sessions and build systems that make the academic journey more meaningful.", focus: "Children · Confidence · Choices · Future", quote: "Zimmedariyan badh gayi hain… par dil aaj bhi classroom mein hi lagta hai." },
    { slug: "anubhav", name: "Anubhav", role: "Mathematics · Student Mentor", title: "The Josh Guy.", image: "assets/Anubhav.jpeg", profileImage: "assets/anubhav_int.jpeg", intro: "Anubhav makes Mathematics feel less intimidating and a little more alive.", bio: "With 4+ years with Genesis, Anubhav has built a strong connection with his students. His support goes beyond class time, helping learners through questions, extra explanations and important examinations.", focus: "Mathematics · Student mentoring · Accessibility", quote: "Jahan dil lag jaaye… wahan padhai bhi lag jaati hai." },
    { slug: "bharti", name: "Bharti", role: "Administration · Branch Management", title: "The Constant.", image: "assets/Bharti.jpeg", profileImage: "assets/bharti_int.jpeg", intro: "Bharti is the constant who keeps the moving parts of Genesis working.", bio: "With 10 years with Genesis, Bharti has grown from someone who once needed guidance into someone who takes decisions, manages a branch and handles the hundred moving pieces that keep a centre running.", focus: "Administration · Branch management · Reliability", quote: "Kuch log sirf saath nahi chalte… waqt ke saath aur mazboot hote jaate hain." },
    { slug: "himanshu", name: "Himanshu", role: "Academic Head · Genesis Zirakpur · Physics Mentor", title: "The One Who Makes It Happen.", image: "assets/Himanshu.jpeg", profileImage: "assets/himanshu_int.jpeg", intro: "When something needs to be handled, Himanshu steps up.", bio: "With 5+ years with Genesis, Himanshu has grown into the role of Academic Head at Genesis Zirakpur, taking responsibility for academics, conversations, follow-ups and the students who depend on the team.", focus: "Physics · Academic leadership · Genesis Zirakpur", quote: "Jab mushkil aaye aur ek naam yaad aaye… wahi apna insaan hota hai." },
    { slug: "inder", name: "Inder", role: "Physics · Student Mentor", title: "The One Who Steps Up.", image: "assets/Inder.jpeg", profileImage: "assets/inder_int.jpeg", intro: "Inder brings the extra class, explanation and practice a student needs.", bio: "With 10 years of Physics experience, Inder understands that teaching is not always what fits into a regular class. His strength is stepping up when students need more time before an important examination.", focus: "Physics · Student mentoring · Extra classes", quote: "Zimmedari di nahi jaati… uthayi jaati hai." },
    { slug: "sahil-paul", name: "Sahil Paul", role: "Biology · Student Mentor", title: "The Quiet Game Changer.", image: "assets/Sahil Paul.jpeg", profileImage: "assets/sahilpaul_int.jpeg", intro: "Sahil brings empathy and discipline to the Biology classroom.", bio: "Sahil is building his journey as an educator with a focus on Biology. He understands that good mentoring means knowing when a student needs encouragement and when they need a little more push.", focus: "Biology · Student mentoring · Empathy and discipline", quote: "Har badi kahani shor se nahi… ek chhoti shuruaat se shuru hoti hai." },
    { slug: "parineeta", name: "Parineeta", role: "English · Student Mentor", title: "More Than an English Teacher.", image: "assets/Parineeta.jpeg", profileImage: "assets/parineeta_int.jpeg", intro: "Parineeta makes it easier for students to speak, ask, make mistakes and try again.", bio: "With 5 years of total experience, Parineeta brings empathy to the classroom and creates an environment where a student feels comfortable enough to ask for help during school and Board preparation.", focus: "English · Student mentoring · Confidence", quote: "Kuch teachers subject padhate hain… kuch bachchon ko zindagi ke baare mein samajhte hain." },
    { slug: "ritika", name: "Ritika", role: "Science · Student Mentor", title: "The Quiet Force.", image: "assets/Ritika.jpeg", profileImage: "assets/ritika_int.jpeg", intro: "Ritika brings consistency, preparation and discipline to everyday learning.", bio: "With 5 years with Genesis, Ritika has become someone the team and students can rely on. She brings care to preparation and seriousness to the small responsibilities that shape a student's progress.", focus: "Science · Student mentoring · Consistency", quote: "Har mazboot imaarat ki buniyad shor nahi machati." },
    { slug: "samridh", name: "Samridh", role: "Mathematics · Student Mentor", title: "Student Success. His Mission.", image: "assets/Samridh.jpeg", profileImage: "assets/samridh_int.jpeg", intro: "For Samridh, a student's result is never just a result.", bio: "With 10+ years of experience, Samridh understands that progress rarely happens in a straight line. His focus is helping students stay supported through the good tests, bad tests and chapters that take a few attempts.", focus: "Mathematics · Student mentoring · Student success", quote: "Unki jeet mein khushi aur unki haar mein dard… bas itna sa rishta hai." },
    { slug: "shivani-rana", name: "Shivani Rana", role: "Academic Head · Genesis Sector 15 · Chemistry Mentor", title: "The Silent Warrior.", image: "assets/Shivani Rana.jpeg", profileImage: "assets/shivani_int.jpeg", intro: "Shivani brings energy with discipline to Chemistry and academic leadership.", bio: "With 8+ years of experience, Shivani keeps showing up for the next class, concept and student. As Academic Head at Genesis Sector 15, she watches the academic journey and the small things that make a big difference.", focus: "Chemistry · Academic leadership · Genesis Sector 15", quote: "Har jung talwar se nahi ladi jaati… kuch jung roz classroom mein jeeti jaati hain." },
    { slug: "puja", name: "Puja", role: "Student & Parent Support", title: "The One Who Makes You Feel at Home.", image: "assets/Puja.jpeg", profileImage: "assets/puja_int.jpeg", intro: "Puja makes students, parents and new visitors feel comfortable at Genesis.", bio: "Puja's role sits at the intersection of students, parents and the people who make a centre feel like more than a place where classes happen. She is building that connection every day.", focus: "Student support · Parent support · Accessibility", quote: "Apnapan waqt nahi dekhta… dil se kaam karne walon ka rishta jaldi ban jaata hai." },
    { slug: "pradeep", name: "Pradeep", role: "Administration & Accounts · Genesis Educates", title: "The Man Who Tells It Like It Is.", image: "assets/Pradeep.jpeg", profileImage: "assets/pradeep_int.jpeg", intro: "Pradeep brings straightforward values, commitment and loyalty to Genesis.", bio: "Fourteen years after joining Genesis as a part-time typist, Pradeep is trusted with accounts and responsibilities that keep the organisation moving. His principle remains simple: do the work honestly and stand by your people.", focus: "Administration · Accounts · Loyalty", quote: "Seedhi baat. Saaf niyat. Aur 14 saal ki wafadaari." }
  ];
})();
